# This is how many times the plugins checks for a safe location before stopping.
# Keep it around 15 or lower for best performance.
max-attempts: 15

# Enable or disable Lands and WorldGuard hooks. These are used to not teleport players in claimed lands or in worldguard regions.
# Enable or disable Vault hook. This is used for teleport prices.
hooks:
  lands: false
  vault: false
  worldguard: true

# This option will only work if Vault hook is enabled.
# Here you can specify the price players have to pay to use /rtp
teleport-price: 100

# Enable this if you want the plugin to use world borders as a max x and z
use-border: true
# These values are used if useBorder is set to false
max-x: 150
max-z: 150

# Specify how long the cooldown for the rtp command should be.
# Set it to '-1' if you want the cooldown to be disabled.
cooldown: -1

# Specify how long the warmup for the rtp command should be.
# Set it to '-1' if you want the warmup to be disabled.
warmup: -1

# These worlds will be used when using '/rtp <player>'.
# You can use the word 'all' and the plugin will use all worlds.
enabled-worlds:
  - world
  - world_nether
  - all