name: RandomTeleport
version: @version@
main: com.blitzoffline.randomteleport.RandomTeleport
api-version: 1.17
softdepend: [PlaceholderAPI, WorldGuard, Lands, Vault]
author: BlitzGamer_88
website: github.com/blitzoffline