name: RandomTeleport
version: @version@
main: com.blitzoffline.randomteleport.RandomTeleport
api-version: 1.13
softdepend: [PlaceholderAPI, WorldGuard, Lands]
author: BlitzGamer_88
website: github.com/blitzoffline